apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
- ../../base
replicas:
- count: 5
  name: deployment
images:
- name: 674582907715.dkr.ecr.ap-northeast-1.amazonaws.com/sample-app
  newTag: feb8967ff6c23078b019c281ce039982cb999a11
